// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurant.DataAccess;

namespace bed_room_finder.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    partial class PostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Restaurant.Models.Restaurant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<float>("bedroomprice")
                        .HasColumnType("real");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("ownername")
                        .HasColumnType("text");

                    b.Property<string>("restaurantname")
                        .HasColumnType("text");

                    b.Property<string>("subcity")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("restaurants");
                });

            modelBuilder.Entity("Restaurant.Models.SmallStarRestaurant", b =>
                {
                    b.Property<int>("ssrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("Restaurantid")
                        .HasColumnType("integer");

                    b.Property<string>("smtype")
                        .HasColumnType("text");

                    b.HasKey("ssrid");

                    b.HasIndex("Restaurantid");

                    b.ToTable("smallStarRestaurants");
                });

            modelBuilder.Entity("Restaurant.Models.SmallStarRestaurant", b =>
                {
                    b.HasOne("Restaurant.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("Restaurantid");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
